name: bottom_sheets
description: 'A new Flutter application.'
version: 1.0.0+1
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cached_network_image: ^0.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/emoji1.png
    - images/emoji2.png
    - images/emoji3.png
    - images/emoji4.png
    - images/emoji5.png
    - images/emoji6.png
    - images/emoji7.png
    - images/emoji8.png
    - images/emoji9.png
    - images/emoji10.png
    - images/emoji11.png
    - images/emoji12.png
    - images/emoji13.png
    - images/emoji14.png
    - images/emoji15.png
    - images/placeholder_image.jpg
